#
# Under Construction
#
name: "Release (dry-run)"
# on: [push, pull_request]
on:
  workflow_run:
    workflows: [Black, Pytest]
    types:
      - completed
jobs:
  pypi_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"  # Latest no need to change as one copy will be delivered
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements_for_uploading.txt
      - run: python setup.py sdist
      - run: twine check dist/alt-profanity-check-1.1.1.tar.gz
