#
# Upload Release with Twine for tags starting with "v".
#
# References:
#
# https://futurestud.io/tutorials/github-actions-run-a-workflow-when-creating-a-tag
#
name: "Release"
on:
  push:
    tags:
      - "v*"
# .github/workflows/ci-cd.yml
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/alt-profanity-check/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
