#
# Upload Release Using Trusted Publishers
#
name: "Release"
'on':
  push:
    tags:
      - v*
jobs:
  build:
    name: "Build package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          pip install -U pip setuptools
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
  pypi-publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: 'https://pypi.org/project/alt-profanity-check/'
    permissions:
      id-token: write
    steps:
      - uses: pypa/gh-action-pypi-publish@release/v1
